// <auto-generated />
using System;
using Data_Logger_1._3.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data_Logger_1._3.Migrations
{
    [DbContext(typeof(ENTITYMASTER))]
    partial class ENTITYMASTERModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Data_Logger_1._3.Models.ACCOUNT", b =>
                {
                    b.Property<int>("accountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyLogo")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("accountID");

                    b.ToTable("ACCOUNT");

                    b.HasData(
                        new
                        {
                            accountID = 1,
                            CompanyAddress = "",
                            CompanyLogo = "",
                            CompanyName = "",
                            Email = "support@datalogger.co.za",
                            FirstName = "admin",
                            IsEmployee = false,
                            IsOnline = false,
                            LastName = "",
                            Password = "pcsx2024",
                            ProfilePic = ""
                        });
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.App_Models.ApplicationClass", b =>
                {
                    b.Property<int>("appID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("accountID")
                        .HasColumnType("INTEGER");

                    b.HasKey("appID");

                    b.HasIndex("accountID");

                    b.ToTable("APPLICATION");

                    b.HasData(
                        new
                        {
                            appID = 1,
                            Category = 0,
                            IsDefault = true,
                            Name = "Qt Creator",
                            accountID = 1
                        },
                        new
                        {
                            appID = 2,
                            Category = 0,
                            IsDefault = true,
                            Name = "Android Studio",
                            accountID = 1
                        },
                        new
                        {
                            appID = 3,
                            Category = 0,
                            IsDefault = true,
                            Name = "Unknown",
                            accountID = 1
                        },
                        new
                        {
                            appID = 4,
                            Category = 0,
                            IsDefault = true,
                            Name = "Visual Studio Community 2022",
                            accountID = 1
                        },
                        new
                        {
                            appID = 5,
                            Category = 1,
                            IsDefault = true,
                            Name = "Krita",
                            accountID = 1
                        },
                        new
                        {
                            appID = 6,
                            Category = 1,
                            IsDefault = true,
                            Name = "Inkscape",
                            accountID = 1
                        },
                        new
                        {
                            appID = 7,
                            Category = 1,
                            IsDefault = true,
                            Name = "Canva",
                            accountID = 1
                        },
                        new
                        {
                            appID = 8,
                            Category = 1,
                            IsDefault = true,
                            Name = "Adobe Illustrator",
                            accountID = 1
                        },
                        new
                        {
                            appID = 9,
                            Category = 2,
                            IsDefault = true,
                            Name = "Da Vinci Resolve",
                            accountID = 1
                        },
                        new
                        {
                            appID = 10,
                            Category = 2,
                            IsDefault = true,
                            Name = "Blender 3D/2D",
                            accountID = 1
                        },
                        new
                        {
                            appID = 11,
                            Category = 2,
                            IsDefault = true,
                            Name = "Powerpoint",
                            accountID = 1
                        },
                        new
                        {
                            appID = 12,
                            Category = 2,
                            IsDefault = true,
                            Name = "Shotcut",
                            accountID = 1
                        },
                        new
                        {
                            appID = 13,
                            Category = 3,
                            IsDefault = true,
                            Name = "Unity",
                            accountID = 1
                        },
                        new
                        {
                            appID = 14,
                            Category = 3,
                            IsDefault = true,
                            Name = "Steam",
                            accountID = 1
                        },
                        new
                        {
                            appID = 15,
                            Category = 3,
                            IsDefault = true,
                            Name = "Data Logger NOTES",
                            accountID = 1
                        },
                        new
                        {
                            appID = 16,
                            Category = 3,
                            IsDefault = true,
                            Name = "Data Logger Checklist",
                            accountID = 1
                        },
                        new
                        {
                            appID = 17,
                            Category = 3,
                            IsDefault = true,
                            Name = "Microsoft Word",
                            accountID = 1
                        },
                        new
                        {
                            appID = 18,
                            Category = 3,
                            IsDefault = true,
                            Name = "REAPER",
                            accountID = 1
                        },
                        new
                        {
                            appID = 19,
                            Category = 3,
                            IsDefault = true,
                            Name = "Notepad",
                            accountID = 1
                        },
                        new
                        {
                            appID = 20,
                            Category = 3,
                            IsDefault = true,
                            Name = "Microsoft Excel",
                            accountID = 1
                        },
                        new
                        {
                            appID = 21,
                            Category = 3,
                            IsDefault = true,
                            Name = "Microsoft Access",
                            accountID = 1
                        },
                        new
                        {
                            appID = 22,
                            Category = 0,
                            IsDefault = true,
                            Name = "IntelliJ",
                            accountID = 1
                        },
                        new
                        {
                            appID = 23,
                            Category = 0,
                            IsDefault = true,
                            Name = "PyCharm",
                            accountID = 1
                        },
                        new
                        {
                            appID = 24,
                            Category = 0,
                            IsDefault = true,
                            Name = "WebStorm",
                            accountID = 1
                        });
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.App_Models.FormatClass", b =>
                {
                    b.Property<int>("formatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("accountID")
                        .HasColumnType("INTEGER");

                    b.HasKey("formatID");

                    b.HasIndex("accountID");

                    b.ToTable("FORMAT");

                    b.HasData(
                        new
                        {
                            formatID = 1,
                            Category = 1,
                            Format = "Paper",
                            accountID = 1
                        },
                        new
                        {
                            formatID = 2,
                            Category = 1,
                            Format = "Digital Canvas",
                            accountID = 1
                        },
                        new
                        {
                            formatID = 3,
                            Category = 1,
                            Format = "Cardboard",
                            accountID = 1
                        },
                        new
                        {
                            formatID = 4,
                            Category = 1,
                            Format = "Wall/Street",
                            accountID = 1
                        },
                        new
                        {
                            formatID = 5,
                            Category = 3,
                            Format = "CD",
                            accountID = 1
                        },
                        new
                        {
                            formatID = 6,
                            Category = 3,
                            Format = "MIDI",
                            accountID = 1
                        },
                        new
                        {
                            formatID = 7,
                            Category = 3,
                            Format = "Digital",
                            accountID = 1
                        },
                        new
                        {
                            formatID = 8,
                            Category = 3,
                            Format = "Tape",
                            accountID = 1
                        },
                        new
                        {
                            formatID = 9,
                            Category = 3,
                            Format = "LP",
                            accountID = 1
                        },
                        new
                        {
                            formatID = 10,
                            Category = 3,
                            Format = "EP",
                            accountID = 1
                        },
                        new
                        {
                            formatID = 11,
                            Category = 3,
                            Format = "Gramophone",
                            accountID = 1
                        },
                        new
                        {
                            formatID = 12,
                            Category = 3,
                            Format = "Digital Download",
                            accountID = 1
                        },
                        new
                        {
                            formatID = 13,
                            Category = 3,
                            Format = "Disc",
                            accountID = 1
                        });
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.App_Models.MeasuringUnitClass", b =>
                {
                    b.Property<int>("unitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("unitID");

                    b.ToTable("UNIT");

                    b.HasData(
                        new
                        {
                            unitID = 1,
                            Unit = "cm"
                        },
                        new
                        {
                            unitID = 2,
                            Unit = "mm"
                        },
                        new
                        {
                            unitID = 3,
                            Unit = "px"
                        },
                        new
                        {
                            unitID = 4,
                            Unit = "in"
                        },
                        new
                        {
                            unitID = 5,
                            Unit = "m"
                        });
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.App_Models.MediumClass", b =>
                {
                    b.Property<int>("mediumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("accountID")
                        .HasColumnType("INTEGER");

                    b.HasKey("mediumID");

                    b.HasIndex("accountID");

                    b.ToTable("MEDIUM");

                    b.HasData(
                        new
                        {
                            mediumID = 1,
                            Category = 1,
                            Medium = "Pencil",
                            accountID = 1
                        },
                        new
                        {
                            mediumID = 2,
                            Category = 1,
                            Medium = "Paint",
                            accountID = 1
                        },
                        new
                        {
                            mediumID = 3,
                            Category = 1,
                            Medium = "Pen",
                            accountID = 1
                        },
                        new
                        {
                            mediumID = 4,
                            Category = 1,
                            Medium = "Pencil Crayon",
                            accountID = 1
                        },
                        new
                        {
                            mediumID = 5,
                            Category = 1,
                            Medium = "Kokie",
                            accountID = 1
                        },
                        new
                        {
                            mediumID = 6,
                            Category = 1,
                            Medium = "Crayon",
                            accountID = 1
                        },
                        new
                        {
                            mediumID = 7,
                            Category = 1,
                            Medium = "Oil Pastel",
                            accountID = 1
                        },
                        new
                        {
                            mediumID = 8,
                            Category = 1,
                            Medium = "Chalk",
                            accountID = 1
                        },
                        new
                        {
                            mediumID = 9,
                            Category = 3,
                            Medium = "A Cappella",
                            accountID = 1
                        },
                        new
                        {
                            mediumID = 10,
                            Category = 3,
                            Medium = "Song",
                            accountID = 1
                        },
                        new
                        {
                            mediumID = 11,
                            Category = 3,
                            Medium = "Orchestral",
                            accountID = 1
                        },
                        new
                        {
                            mediumID = 12,
                            Category = 3,
                            Medium = "Game Engine",
                            accountID = 1
                        });
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.App_Models.OutputClass", b =>
                {
                    b.Property<int>("outputID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("accountID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("appID")
                        .HasColumnType("INTEGER");

                    b.HasKey("outputID");

                    b.HasIndex("accountID");

                    b.HasIndex("appID");

                    b.ToTable("OUTPUT");

                    b.HasData(
                        new
                        {
                            outputID = 1,
                            Category = 0,
                            Name = "Console Application",
                            accountID = 1,
                            appID = 1
                        },
                        new
                        {
                            outputID = 2,
                            Category = 0,
                            Name = "Widgets Application",
                            accountID = 1,
                            appID = 1
                        },
                        new
                        {
                            outputID = 3,
                            Category = 0,
                            Name = "QtQuick Application",
                            accountID = 1,
                            appID = 1
                        },
                        new
                        {
                            outputID = 4,
                            Category = 0,
                            Name = "APK (*.apk)",
                            accountID = 1,
                            appID = 2
                        },
                        new
                        {
                            outputID = 5,
                            Category = 0,
                            Name = "USB",
                            accountID = 1,
                            appID = 2
                        },
                        new
                        {
                            outputID = 6,
                            Category = 0,
                            Name = "Emulator (*.exe)",
                            accountID = 1,
                            appID = 2
                        },
                        new
                        {
                            outputID = 7,
                            Category = 0,
                            Name = "C# Application (*.exe)",
                            accountID = 1,
                            appID = 4
                        },
                        new
                        {
                            outputID = 8,
                            Category = 0,
                            Name = "C++ Application (*.exe)",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 9,
                            Category = 0,
                            Name = "Java Application (*.exe)",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 10,
                            Category = 0,
                            Name = "Database (*.db)",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 11,
                            Category = 0,
                            Name = "Database (SQL, Oracle)",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 12,
                            Category = 1,
                            Name = "PNG",
                            accountID = 1,
                            appID = 5
                        },
                        new
                        {
                            outputID = 13,
                            Category = 1,
                            Name = "JPG",
                            accountID = 1,
                            appID = 5
                        },
                        new
                        {
                            outputID = 14,
                            Category = 1,
                            Name = "SVG",
                            accountID = 1,
                            appID = 6
                        },
                        new
                        {
                            outputID = 15,
                            Category = 1,
                            Name = "GIF",
                            accountID = 1,
                            appID = 5
                        },
                        new
                        {
                            outputID = 16,
                            Category = 1,
                            Name = "PDF",
                            accountID = 1,
                            appID = 7
                        },
                        new
                        {
                            outputID = 17,
                            Category = 1,
                            Name = "TIFF",
                            accountID = 1,
                            appID = 8
                        },
                        new
                        {
                            outputID = 18,
                            Category = 1,
                            Name = "PSD",
                            accountID = 1,
                            appID = 8
                        },
                        new
                        {
                            outputID = 19,
                            Category = 1,
                            Name = "WEBP",
                            accountID = 1,
                            appID = 8
                        },
                        new
                        {
                            outputID = 20,
                            Category = 2,
                            Name = "MP4",
                            accountID = 1,
                            appID = 9
                        },
                        new
                        {
                            outputID = 21,
                            Category = 2,
                            Name = "AVI",
                            accountID = 1,
                            appID = 9
                        },
                        new
                        {
                            outputID = 22,
                            Category = 2,
                            Name = "MKV",
                            accountID = 1,
                            appID = 9
                        },
                        new
                        {
                            outputID = 23,
                            Category = 2,
                            Name = "TS",
                            accountID = 1,
                            appID = 9
                        },
                        new
                        {
                            outputID = 24,
                            Category = 2,
                            Name = "WEBM",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 25,
                            Category = 3,
                            Name = "PDF",
                            accountID = 1,
                            appID = 17
                        },
                        new
                        {
                            outputID = 26,
                            Category = 3,
                            Name = "WORD",
                            accountID = 1,
                            appID = 17
                        },
                        new
                        {
                            outputID = 27,
                            Category = 3,
                            Name = "TEXT FILE (*.txt)",
                            accountID = 1,
                            appID = 17
                        },
                        new
                        {
                            outputID = 28,
                            Category = 3,
                            Name = "HTML (*.html)",
                            accountID = 1,
                            appID = 17
                        },
                        new
                        {
                            outputID = 29,
                            Category = 3,
                            Name = "XPS (*.xps)",
                            accountID = 1,
                            appID = 17
                        },
                        new
                        {
                            outputID = 30,
                            Category = 3,
                            Name = "EXCEL FILE (*.xlsx)",
                            accountID = 1,
                            appID = 20
                        },
                        new
                        {
                            outputID = 31,
                            Category = 3,
                            Name = "ACCESS FILE (*.accdb)",
                            accountID = 1,
                            appID = 21
                        },
                        new
                        {
                            outputID = 32,
                            Category = 3,
                            Name = "MP3",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 33,
                            Category = 3,
                            Name = "WAV",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 34,
                            Category = 3,
                            Name = "AAC",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 35,
                            Category = 3,
                            Name = "M4A",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 36,
                            Category = 3,
                            Name = "OGG",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 37,
                            Category = 3,
                            Name = "Note",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 38,
                            Category = 3,
                            Name = "Check List",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 39,
                            Category = 3,
                            Name = "PNG",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 40,
                            Category = 3,
                            Name = "JPG",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 41,
                            Category = 3,
                            Name = "EXE (*.exe)",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 42,
                            Category = 0,
                            Name = "JavaScript (*.js)",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 43,
                            Category = 0,
                            Name = "Kotlin Application (*.kt)",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 44,
                            Category = 0,
                            Name = "Python Application (*.py)",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 45,
                            Category = 0,
                            Name = "React App (*.jsx | *.js)",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 46,
                            Category = 0,
                            Name = "PHP (*.php)",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 47,
                            Category = 0,
                            Name = "CSS (*.css)",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            outputID = 48,
                            Category = 0,
                            Name = "Tailwind CSS",
                            accountID = 1,
                            appID = 3
                        });
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.App_Models.ProjectClass", b =>
                {
                    b.Property<int>("projectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("accountID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("appID")
                        .HasColumnType("INTEGER");

                    b.HasKey("projectID");

                    b.HasIndex("accountID");

                    b.HasIndex("appID");

                    b.ToTable("PROJECT");

                    b.HasData(
                        new
                        {
                            projectID = 1,
                            Category = 0,
                            IsDefault = true,
                            Name = "Unknown",
                            accountID = 1,
                            appID = 3
                        });
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.App_Models.SubjectClass", b =>
                {
                    b.Property<int>("subjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("accountID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("appID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("projectID")
                        .HasColumnType("INTEGER");

                    b.HasKey("subjectID");

                    b.HasIndex("accountID");

                    b.HasIndex("appID");

                    b.HasIndex("projectID");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            subjectID = 1,
                            Category = 0,
                            Subject = "No Subject",
                            accountID = 1,
                            appID = 3,
                            projectID = 1
                        });
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.App_Models.TypeClass", b =>
                {
                    b.Property<int>("typeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("accountID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("appID")
                        .HasColumnType("INTEGER");

                    b.HasKey("typeID");

                    b.HasIndex("accountID");

                    b.HasIndex("appID");

                    b.ToTable("TYPE");

                    b.HasData(
                        new
                        {
                            typeID = 1,
                            Category = 0,
                            Name = "NONE",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 2,
                            Category = 0,
                            Name = "Build",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 3,
                            Category = 0,
                            Name = "Runtime",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 4,
                            Category = 0,
                            Name = "Sync",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 5,
                            Category = 0,
                            Name = "Build",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 6,
                            Category = 0,
                            Name = "Runtime",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 7,
                            Category = 0,
                            Name = "Compilation",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 8,
                            Category = 0,
                            Name = "Runtime",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 9,
                            Category = 1,
                            Name = "NONE",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 10,
                            Category = 1,
                            Name = "Artwork",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 11,
                            Category = 1,
                            Name = "Doodle",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 12,
                            Category = 1,
                            Name = "Graphic Design",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 13,
                            Category = 1,
                            Name = "Resource",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 14,
                            Category = 1,
                            Name = "Portfolio",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 15,
                            Category = 2,
                            Name = "NONE",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 16,
                            Category = 2,
                            Name = "Film",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 17,
                            Category = 2,
                            Name = "Doodle",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 18,
                            Category = 2,
                            Name = "Assignment",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 19,
                            Category = 3,
                            Name = "Music",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 20,
                            Category = 3,
                            Name = "Poetry",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 21,
                            Category = 3,
                            Name = "Mantra",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 22,
                            Category = 3,
                            Name = "Boardgame",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 23,
                            Category = 3,
                            Name = "Video game",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 24,
                            Category = 3,
                            Name = "Card game",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 25,
                            Category = 3,
                            Name = "Game - Design ONLY",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 26,
                            Category = 3,
                            Name = "Document",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 27,
                            Category = 3,
                            Name = "Invitation",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 28,
                            Category = 3,
                            Name = "Mail",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 29,
                            Category = 3,
                            Name = "Report",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 30,
                            Category = 3,
                            Name = "Doodle",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 31,
                            Category = 3,
                            Name = "Novel",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 32,
                            Category = 3,
                            Name = "Questionnaire",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 33,
                            Category = 3,
                            Name = "CV",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 34,
                            Category = 3,
                            Name = "Web page",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 35,
                            Category = 3,
                            Name = "Presentation",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 36,
                            Category = 3,
                            Name = "Spreadsheet",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 37,
                            Category = 3,
                            Name = "Notes",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 38,
                            Category = 3,
                            Name = "Access Database",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 39,
                            Category = 3,
                            Name = "Note",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 40,
                            Category = 3,
                            Name = "Check List",
                            accountID = 1,
                            appID = 3
                        },
                        new
                        {
                            typeID = 41,
                            Category = 0,
                            Name = "Exception",
                            accountID = 1,
                            appID = 3
                        });
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.CheckList", b =>
                {
                    b.Property<int>("logID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("accountID")
                        .HasColumnType("INTEGER");

                    b.HasKey("logID");

                    b.HasIndex("accountID");

                    b.ToTable("CHECKLIST");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.CheckListItem", b =>
                {
                    b.Property<int>("itemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChecklistlogID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("accountID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("logID")
                        .HasColumnType("INTEGER");

                    b.HasKey("itemID");

                    b.HasIndex("ChecklistlogID");

                    b.HasIndex("accountID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.FeedbackMessage", b =>
                {
                    b.Property<int>("feedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanContact")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateReported")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoFeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("accountID")
                        .HasColumnType("INTEGER");

                    b.HasKey("feedbackID");

                    b.HasIndex("accountID");

                    b.ToTable("FEEDBACK");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.LOG", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<int>("accountID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("appID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("outputID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("projectID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("typeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("accountID");

                    b.HasIndex("appID");

                    b.HasIndex("outputID");

                    b.HasIndex("projectID");

                    b.HasIndex("typeID");

                    b.ToTable("LOG");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.PostIt", b =>
                {
                    b.Property<int>("postItID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ERCaptureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SOCaptureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Suggestion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("accountID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("logID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("subjectID")
                        .HasColumnType("INTEGER");

                    b.HasKey("postItID");

                    b.HasIndex("accountID");

                    b.HasIndex("logID");

                    b.HasIndex("subjectID");

                    b.ToTable("PostIt");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.CodingLOG", b =>
                {
                    b.HasBaseType("Data_Logger_1._3.Models.LOG");

                    b.Property<int>("Bugs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.ToTable("CodingLOG");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.FilmLOG", b =>
                {
                    b.HasBaseType("Data_Logger_1._3.Models.LOG");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.ToTable("FilmLOG");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.GraphicsLOG", b =>
                {
                    b.HasBaseType("Data_Logger_1._3.Models.LOG");

                    b.Property<string>("Brush")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DPI")
                        .HasColumnType("REAL");

                    b.Property<string>("Depth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.Property<int>("formatID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("mediumID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("unitID")
                        .HasColumnType("INTEGER");

                    b.HasIndex("formatID");

                    b.HasIndex("mediumID");

                    b.HasIndex("unitID");

                    b.ToTable("GraphicsLOG");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.NotesLOG", b =>
                {
                    b.HasBaseType("Data_Logger_1._3.Models.LOG");

                    b.ToTable("NotesLOG");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.AndroidCodingLOG", b =>
                {
                    b.HasBaseType("Data_Logger_1._3.Models.CodingLOG");

                    b.Property<DateTime>("AllProjects")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConfigureBuild")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoadBuild")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RunBuild")
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartingGradleDaemon")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Sync")
                        .HasColumnType("TEXT");

                    b.ToTable("AndroidCodingLOG");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.FlexiNotesLOG", b =>
                {
                    b.HasBaseType("Data_Logger_1._3.Models.NotesLOG");

                    b.Property<int>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("flexinotetype")
                        .HasColumnType("INTEGER");

                    b.Property<int>("formatID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("gamingcontext")
                        .HasColumnType("INTEGER");

                    b.Property<int>("mediumID")
                        .HasColumnType("INTEGER");

                    b.HasIndex("formatID");

                    b.HasIndex("mediumID");

                    b.ToTable("FlexiNotesLOG");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.NoteItem", b =>
                {
                    b.HasBaseType("Data_Logger_1._3.Models.NotesLOG");

                    b.Property<int?>("CheckListID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoteContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("CheckListID")
                        .IsUnique();

                    b.ToTable("NoteItem");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.App_Models.ApplicationClass", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.ACCOUNT", "User")
                        .WithMany()
                        .HasForeignKey("accountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.App_Models.FormatClass", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.ACCOUNT", "User")
                        .WithMany()
                        .HasForeignKey("accountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.App_Models.MediumClass", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.ACCOUNT", "User")
                        .WithMany()
                        .HasForeignKey("accountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.App_Models.OutputClass", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.ACCOUNT", "User")
                        .WithMany()
                        .HasForeignKey("accountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Logger_1._3.Models.App_Models.ApplicationClass", "Application")
                        .WithMany()
                        .HasForeignKey("appID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.App_Models.ProjectClass", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.ACCOUNT", "User")
                        .WithMany()
                        .HasForeignKey("accountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Logger_1._3.Models.App_Models.ApplicationClass", "Application")
                        .WithMany()
                        .HasForeignKey("appID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.App_Models.SubjectClass", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.ACCOUNT", "User")
                        .WithMany()
                        .HasForeignKey("accountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Logger_1._3.Models.App_Models.ApplicationClass", "Application")
                        .WithMany()
                        .HasForeignKey("appID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Logger_1._3.Models.App_Models.ProjectClass", "Project")
                        .WithMany()
                        .HasForeignKey("projectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.App_Models.TypeClass", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.ACCOUNT", "User")
                        .WithMany()
                        .HasForeignKey("accountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Logger_1._3.Models.App_Models.ApplicationClass", "Application")
                        .WithMany()
                        .HasForeignKey("appID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.CheckList", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.ACCOUNT", "Author")
                        .WithMany()
                        .HasForeignKey("accountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.CheckListItem", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.CheckList", "Checklist")
                        .WithMany("Items")
                        .HasForeignKey("ChecklistlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Logger_1._3.Models.ACCOUNT", "Author")
                        .WithMany()
                        .HasForeignKey("accountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.FeedbackMessage", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.ACCOUNT", "User")
                        .WithMany()
                        .HasForeignKey("accountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.LOG", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.ACCOUNT", "Author")
                        .WithMany()
                        .HasForeignKey("accountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Logger_1._3.Models.App_Models.ApplicationClass", "Application")
                        .WithMany()
                        .HasForeignKey("appID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Logger_1._3.Models.App_Models.OutputClass", "Output")
                        .WithMany()
                        .HasForeignKey("outputID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Logger_1._3.Models.App_Models.ProjectClass", "Project")
                        .WithMany()
                        .HasForeignKey("projectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Logger_1._3.Models.App_Models.TypeClass", "Type")
                        .WithMany()
                        .HasForeignKey("typeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Author");

                    b.Navigation("Output");

                    b.Navigation("Project");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.PostIt", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.ACCOUNT", "Author")
                        .WithMany()
                        .HasForeignKey("accountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Logger_1._3.Models.LOG", "Log")
                        .WithMany("PostItList")
                        .HasForeignKey("logID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Logger_1._3.Models.App_Models.SubjectClass", "Subject")
                        .WithMany()
                        .HasForeignKey("subjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Log");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.CodingLOG", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.LOG", null)
                        .WithOne()
                        .HasForeignKey("Data_Logger_1._3.Models.CodingLOG", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.FilmLOG", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.LOG", null)
                        .WithOne()
                        .HasForeignKey("Data_Logger_1._3.Models.FilmLOG", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.GraphicsLOG", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.LOG", null)
                        .WithOne()
                        .HasForeignKey("Data_Logger_1._3.Models.GraphicsLOG", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Logger_1._3.Models.App_Models.FormatClass", "Format")
                        .WithMany()
                        .HasForeignKey("formatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Logger_1._3.Models.App_Models.MediumClass", "Medium")
                        .WithMany()
                        .HasForeignKey("mediumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Logger_1._3.Models.App_Models.MeasuringUnitClass", "Unit")
                        .WithMany()
                        .HasForeignKey("unitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Format");

                    b.Navigation("Medium");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.NotesLOG", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.LOG", null)
                        .WithOne()
                        .HasForeignKey("Data_Logger_1._3.Models.NotesLOG", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.AndroidCodingLOG", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.CodingLOG", null)
                        .WithOne()
                        .HasForeignKey("Data_Logger_1._3.Models.AndroidCodingLOG", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.FlexiNotesLOG", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.NotesLOG", null)
                        .WithOne()
                        .HasForeignKey("Data_Logger_1._3.Models.FlexiNotesLOG", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Logger_1._3.Models.App_Models.FormatClass", "Format")
                        .WithMany()
                        .HasForeignKey("formatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Logger_1._3.Models.App_Models.MediumClass", "Medium")
                        .WithMany()
                        .HasForeignKey("mediumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Format");

                    b.Navigation("Medium");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.NoteItem", b =>
                {
                    b.HasOne("Data_Logger_1._3.Models.CheckList", "Checklist")
                        .WithOne("NoteItem")
                        .HasForeignKey("Data_Logger_1._3.Models.NoteItem", "CheckListID");

                    b.HasOne("Data_Logger_1._3.Models.NotesLOG", null)
                        .WithOne()
                        .HasForeignKey("Data_Logger_1._3.Models.NoteItem", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.CheckList", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("NoteItem")
                        .IsRequired();
                });

            modelBuilder.Entity("Data_Logger_1._3.Models.LOG", b =>
                {
                    b.Navigation("PostItList");
                });
#pragma warning restore 612, 618
        }
    }
}
