<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageIcon>core_package_icon.png</PackageIcon>
    <Version>1.3.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\Assets\icons\core_package_icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
