<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Company>Data Logger</Company>
    <PackageIcon>design_package_icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\PDF\Red Hat Display Bold Italic.ttf" />
    <None Remove="Fonts\PDF\Red Hat Display Bold.ttf" />
    <None Remove="Fonts\PDF\Red Hat Display Italic.ttf" />
    <None Remove="Fonts\PDF\Red Hat Display Medium.ttf" />
    <None Remove="Fonts\PDF\Red Hat Display SemiBold Italic.ttf" />
    <None Remove="Fonts\PDF\Red Hat Display SemiBold.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Brushes\Colours.xaml" />
    <Page Remove="Styles\Buttons.xaml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Assets\icons\design_package_icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Brushes\Colours.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Resource>
    <Resource Include="Fonts\PDF\Red Hat Display Bold Italic.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\PDF\Red Hat Display Bold.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\PDF\Red Hat Display Italic.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\PDF\Red Hat Display Medium.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\PDF\Red Hat Display SemiBold Italic.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\PDF\Red Hat Display SemiBold.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Red Hat Display.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Zekton Bold Italic.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Zekton Bold.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Zekton Italic.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Zekton Light.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Zekton.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Styles\Buttons.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Resource>
  </ItemGroup>

</Project>
