<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<AssemblyName>DataLoggerSetup</AssemblyName>
		<ApplicationIcon>installericon.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Authors>ninjadevpunk</Authors>
		<Version>$(VersionPrefix)</Version>
		<Company>Data Logger</Company>
		<Product>Data Logger Installer</Product>
		<AssemblyVersion>1.3.0</AssemblyVersion>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="appsettings.DevMode.json" />
		<None Remove="appsettings.json" />
		<None Remove="Assets\dls_icon.ico" />
		<None Remove="Setup.exe" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="installericon.ico" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Commands\" />
		<Folder Include="Services\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="WPFTransitionals" Version="1.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Design\Design.csproj" />
		<ProjectReference Include="..\FileSys\FileSys.csproj" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Assets\dls_icon.ico">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<LogicalName>dls_icon.ico</LogicalName>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="appsettings.DevMode.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<LogicalName>appsettings.DevMode.json</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="appsettings.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<LogicalName>appsettings.json</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Setup.exe">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<LogicalName>Setup.exe</LogicalName>
		</EmbeddedResource>
	</ItemGroup>

</Project>
